---
- name: Pull image from repository
  docker_image:
    name: ahnoamu/ahnoamu-yolo-client:v1.0.0
    source: pull

- name: Ensure the network 'app-net' exists
  docker_network:
    name: app-net
    state: present
        
- name: Create Node.js Frontend Container
  docker_container:
    name: ahnoamu-yolo-client
    image: ahnoamu/ahnoamu-yolo-client:v1.0.0
    networks:
      - name: app-net
    ports:
      - "3000:3000"
    command: "npm start"
  become: yes
