---
- name: Pull image from repository
  docker_image:
    name: ahnoamu/ahnoamu-yolo-backend:v1.0.0
    source: pull

- name: Ensure the network 'app-net' exists
  docker_network:
    name: app-net
    state: present
        
- name: Create Node.js Backend Container
  docker_container:
    name: ahnoamu-yolo-backend
    image: ahnoamu/ahnoamu-yolo-backend:v1.0.0
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    command: "node server.js"
  become: yes
