---
- name: Run MongoDB Container
  docker_container:
    name: app-mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./app-mongo-data:/data/db
    networks:
      - name: app-net
    command: "systemctl start mongod || service mongod start"
      
  tags:
    - database
    - backend