# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ahnoamu-yolo-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ahnoamu-yolo-backend
  template:
    metadata:
      labels:
        app: ahnoamu-yolo-backend
    spec:
      containers:
        - name: ahnoamu-yolo-backend
          image: docker.io/ahnoamu/ahnoamu-yolo-backend:v1.0.1
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://app-ip-mongo:27017"  # MongoDB service URL listening on port 27017; app-ip-mongo: label of the mongoDB pod
          stdin: true  # Enable interactive terminal
          tty: true  # Enable a pseudo-terminal (like -it in Docker)

---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: ahnoamu-yolo-backend
spec:
  type: LoadBalancer  # Exposes the backend externally via a cloud load balancer
  selector:
    app: ahnoamu-yolo-backend
  ports:
    - protocol: TCP
      port: 5000       # Port inside the service (exposes the backend to the network)
      targetPort: 5000  # Container's port
      nodePort: 32000   # Exposes the service on port 32000 of Minikube node

