# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ip-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-ip-mongo
  template:
    metadata:
      labels:
        app: app-ip-mongo
    spec:
      containers:
        - name: app-ip-mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc  # This should be an existing PersistentDisk in your GCP project


---
# MongoDB PersistentVolumeClaim (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---
# MongoDB Persistent Volume (PV) on GCP Persistent Disk
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Keeps disk - deletion of the database pod does not lead to the loss of items
  gcePersistentDisk:
    pdName: my-mongo-disk    # This should be an existing PersistentDisk in your GCP project
    fsType: ext4



---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: app-ip-mongo
spec:
  type: ClusterIP
  selector:
    app: app-ip-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017  
