# MongoDB Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-ip-mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-ip-mongo
  template:
    metadata:
      labels:
        app: app-ip-mongo
    spec:
      containers:
        - name: app-ip-mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-storage-0    # Dynamically generated name
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: ""
        volumeMode: Filesystem
        persistentVolumeReclaimPolicy: Retain   # Deletion of the database pod does not lead to the loss of items



---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: app-ip-mongo
spec:
  type: ClusterIP
  selector:
    app: app-ip-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017  
